# swagger.yml

openapi: 3.0.0
info:
  title: "PadleTime Flask REST API"
  description: "An API for Padle"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Client:
      type: "object"
      required:
        - first_name
        - last_name
        - password
        - email
        - phone_number
        - nif
        - role
      properties:
        first_name:
          type: "string"
        last_name:
          type: "string"
        password:
          type: "string"
        email:
          type: "string"
        nif:
          type: "number"
        phone_number:
          type: "string"
        role:
          type: "string"

paths:
  /client/register:
    post:
      operationId: "api.register_user"
      tags:
        - Client
      summary: "Create a client"
      requestBody:
        description: "Client to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "client"
              $ref: "#/components/schemas/Client"
      responses:
        "201":
          description: "Successfully created client"